
# html lang
language: zh-Hans

# main menu navigation
menu:
  home: /
  archives: /archives
  tags: /tags
  categories: /categories
  #search: /search
  about: /about
  # rss: /atom.xml

# Miscelaneous
favicon: /logo.jpeg

# stylesheets loaded in the <head>
stylesheets:
# - /css/normalize.css
- //cdn.bootcss.com/pure/1.0.0/pure-min.css
- /css/xoxo.css

# scripts loaded in the end of the body
scripts:
#- //cdn.bootcss.com/zepto/1.2.0/zepto.min.js
#- /js/xoxo.js

# switch
show_excerpt: true
show_date: true
#footer
index_page: dantes1844.github.io
main_site: dantes1844.github.io
github: https://github.com/dantes1844/
